[pytest]
env = 
    ; NOTE: Without this follwoing import failes during debugging in vscode
    ; and causes tests durring regural run to hang forever (and I have no idea why)
    ; from tool.lsp_utils import update_sys_path
    PYTHONPATH=bundled
 